### ISSUE TITLE
“Call to a member function setAttributes”

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/postmark#10]
I’ve had to fallback to SMTP as this adaptor always throws the following exception when deployed on Fortrabbit.

```
2019-07-17 19:13:08 [-][-][-][error][Error] Error: Call to a member function setAttributes() on null in /srv/app/htdocs/vendor/craftcms/cms/src/base/Plugin.php:213
Stack trace:
#0 /srv/app/htdocs/vendor/yiisoft/yii2/base/Component.php(180): craft\base\Plugin->setSettings(Array)
#1 /srv/app/htdocs/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('settings', Array)
#2 /srv/app/htdocs/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craftcms\postmark\Plugin), Array)
#3 /srv/app/htdocs/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /srv/app/htdocs/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('postmark', Object(craft\web\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('postmark', Object(craft\web\Application), Array)
#6 /srv/app/htdocs/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#7 /srv/app/htdocs/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craftcms\\postma...', Array, Array)
#8 /srv/app/htdocs/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craftcms\\postma...', Array, Array)
#9 /srv/app/htdocs/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#10 /srv/app/htdocs/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('postmark', Array)
#11 /srv/app/htdocs/vendor/craftcms/cms/src/base/ApplicationTrait.php(1323): craft\services\Plugins->loadPlugins()
#12 /srv/app/htdocs/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#13 /srv/app/htdocs/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#14 /srv/app/htdocs/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /srv/app/htdocs/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#16 [internal function]: craft\web\Application->__construct(Array)
#17 /srv/app/htdocs/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#18 /srv/app/htdocs/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#19 /srv/app/htdocs/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#20 /srv/app/htdocs/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#21 /srv/app/htdocs/vendor/craftcms/cms/bootstrap/web.php(52): require('/srv/app/puresp...')
#22 /srv/app/htdocs/web/index.php(20): require('/srv/app/puresp...')
#23 {main}
```

I’ll admit I’ve not spent any time debugging, however, it _looks_ like a composer issue. Running `composer install` didn’t help though.

Any thoughts on this?

**Comment by joshuabaker** [comment]
> This looks like a Postmark bug so I’ll fix it over there, but in the meantime you should be able to fix this locally by clearing out your `settings` column value for the `postmark` plugin in your `plugins` table.

**Comment by joshuabaker** [comment]
@brandonkelly We don’t have a `settings` column in the `plugins` table. It’s missing on all of the other Craft sites I’ve checked too. Should that column definitely exist, or could this be something else?
